export { default as applicationBg } from "./imgs/application-bg.png";
export { default as varosLogo } from "./imgs/Varos Logotipo.svg";
export { default as navToggle } from "./imgs/nav-toggle.png";
export { default as valuation } from "./imgs/Valuation 2.0.png";
export { default as formVector } from "./imgs/form-vector.svg";
export { default as stars } from "./imgs/stars.svg";
export { default as bulb } from "./imgs/mdi-light_lightbulb.svg";
export { default as chart } from "./imgs/mdi-light_chart-line.svg";
export { default as graph } from "./imgs/mdi-light_signal.svg";
export { default as cog } from "./imgs/mdi-light_cog.svg";
export { default as arrowBox } from "./imgs/arrow-box.svg";
export { default as layers } from "./imgs/mdi-light_layers.svg";
export { default as handleLeft } from "./imgs/mdi-light_chevron-down.svg";
export { default as handleRight } from "./imgs/mdi-light_chevron-right.svg";
